### ISSUE TITLE
Would it work on Rails 4.2 with Turbolinks 2.5.0?

### ISSUE THREAD

**Issue by BogdanChayka** [benoitongit/vue-on-rails#1]
That would be great to know, because i really want to use it, but i don't know if i would experience issues with turbolinks. Can't upgrade the whole project yet.

Best wishes

**Comment by benoitongit** [comment]
It should yes, I have never tested though. But I don't see foresee any problem.

On the JS side you'll have to use it like this:
`$(document).on('ready page:load', function(event) {
    VueOnRails.mountComponents();
});`

`$(document).on('page:after-remove', function(event) {
    VueOnRails.destroyComponents();
});`

Let me know if you have any issue, I'll be happy to help/fix.
